services:
  - type: web
    name: mirza-spree-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.nmddtxibpsbtswxnienm:Punit1803.com@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_LEVEL
        value: info
      - key: SPREE_ADMIN_EMAIL
        value: admin@mirzafootwear.com
      - key: SPREE_ADMIN_PASSWORD
        value: MirzaAdmin2026!
      - key: SOLID_QUEUE_IN_PUMA
        value: "true"
